<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:aop="http://www.springframework.org/schema/aop"
    xsi:schemaLocation="
        http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/aop https://www.springframework.org/schema/aop/spring-aop.xsd">

	<aop:config>
				<aop:aspect id="dataLayerExceptionAspect" ref="dataExceptionHandler" order="1">
			<aop:pointcut id="dataLayerPointCut" expression="execution(* com.cognizant.cosmos.datajpa.core.datajpa.dao.impl.DatajpaCoreDaoImpl.*(..))"/>
        	<aop:after-throwing pointcut-ref="dataLayerPointCut" method="handleException" throwing="error"/>
		</aop:aspect>
		<aop:aspect id="serviceLayerExceptionAspect" ref="serviceExceptionHandler" order="2">
			<aop:pointcut id="serviceLayerPointCut" expression="execution(* com.cognizant.cosmos.datajpa.core.datajpa.service.impl.DatajpaCoreServiceImpl.*(..))"/>
        	<aop:after-throwing pointcut-ref="serviceLayerPointCut" method="handleException" throwing="error"/>
		</aop:aspect>
		<aop:aspect id="controllerLayerExceptionAspect" ref="controllerExceptionHandler" order="3">
			<aop:pointcut id="controllerLayerPointCut" expression="execution(* com.cognizant.cosmos.datajpa.core.datajpa.controller.DatajpaCoreServiceController.*(..))"/>
        	<aop:after-throwing pointcut-ref="controllerLayerPointCut" method="handleException" throwing="error"/>
		</aop:aspect>
	</aop:config>

	<bean id="dataExceptionHandler" class="com.cognizant.cosmos.datajpa.core.datajpa.exception.impl.DataExceptionHandler" />
	<bean id="serviceExceptionHandler" class="com.cognizant.cosmos.datajpa.core.datajpa.exception.impl.ServiceExceptionHandler" />
	<bean id="controllerExceptionHandler" class="com.cognizant.cosmos.datajpa.core.datajpa.exception.impl.ControllerExceptionHandler" />
</beans>
